$ErrorActionPreference = "Stop"
$ProgressPreference = "SilentlyContinue"

# Nebflow Windows installer - script v2
# ---------------------------------------------------------------
# ScriptVersion : installer version (written into the local install
#                 manifest for `nebflow update` and diagnostics).
# Pipeline      : [1/7] java -> [2/7] git -> [3/7] jar -> [4/7] rg ->
#                 [5/7] voice model -> [6/7] launcher -> [7/7] config.
# Idempotent    : safe to re-run; installed/satisfied deps are detected
#                 and skipped.
# Flags         : -Beta | --channel=beta | -Cn | -Global | -VerboseFlag
#                 (irm|iex pipe: env CHANNEL=beta / REGION=cn /
#                 NEBFLOW_VERBOSE=1)
# Exit codes    : 0 ok | 10 version resolve | 11 java install |
#                 12 jar download
# ---------------------------------------------------------------

# -- Brand values (L2 rebrand): rendered from repo-root brand.conf at -------
# -- release time (scripts/render-brand.sh); do not edit by hand. -----------
# The runtime dual-reads legacy names (L3), so rendering NEW values here
# keeps existing user data working - old dirs/env/config fall back.
$ProductName = "Nebflow"
$LowerName = "nebflow"
$CosBucket = "nebflow-releases-1411212853"
$HomeDir = ".nebflow"
$ConfigFile = "nebflow.json"
$WrapperName = "nebflow"
$CosBaseCn = "https://$CosBucket.cos.ap-nanjing.myqcloud.com"
# 仓库已转 private（#29，2026-09-01）：GitHub Releases 未认证下载 404——
# Nebflow jar 下载/版本解析统一走 COS（单一源）。第三方依赖
# （Temurin JDK/Git for Windows/ripgrep）与仓库 private 无关，仍走各自公共源。

$ScriptVersion = "2.0.0"
$RgVersion = "14.1.1"
$JdkMajorRequired = 17   # runtime floor; fresh installs target OpenJDK 21
# Batch 2 (v2): all third-party deps mirrored on COS under the deps/ prefix
# (single primary source for every region; upstream sources demoted to
# fallback). Integrity via deps/checksums.txt (sha256, generated by
# scripts/upload-deps.sh at upload time).
$CosDepsBase = "$CosBaseCn/deps"

# ---- checksum machinery (deps/ integrity, batch 2) ------------------------
$script:ChecksumsContent = $null

function Get-ExpectedChecksum($name) {
    if ($null -eq $script:ChecksumsContent) {
        try {
            $script:ChecksumsContent = (Invoke-WebRequest -Uri "$CosDepsBase/checksums.txt" -UseBasicParsing -TimeoutSec 15).Content
            Write-V "Loaded deps/checksums.txt from COS."
        } catch {
            $script:ChecksumsContent = ""
            Write-V "deps/checksums.txt unreachable - checksum verification degraded."
        }
    }
    if (-not $script:ChecksumsContent) { return $null }
    foreach ($line in ($script:ChecksumsContent -split "`n")) {
        $parts = $line.Trim() -split '\s+', 2
        if ($parts.Count -eq 2 -and $parts[1] -eq $name) { return $parts[0].ToLower() }
    }
    return $null
}

# Returns "ok" | "bad" | "unknown"
function Test-FileChecksum($path, $name) {
    $expected = Get-ExpectedChecksum $name
    if (-not $expected) { return "unknown" }
    $actual = (Get-FileHash -Path $path -Algorithm SHA256).Hash.ToLower()
    if ($actual -eq $expected) { Write-V "Checksum OK: $name"; return "ok" }
    Write-Warn2 "Checksum mismatch for $name (expected $expected, got $actual)"
    return "bad"
}

function Write-ChecksumHint($name) {
    $h = Get-ExpectedChecksum $name
    if ($h) { Write-Warn2 "       sha256: $h" }
}

# Multi-source download with checksum verification (COS first by convention).
#   Get-FileFromSources -Path <target> -Name <manifest-name> -Urls <url,...>
# Returns $true when a source succeeded (checksum ok or unknown).
function Get-FileFromSources {
    param([string]$Path, [string]$Name, [string[]]$Urls)
    foreach ($url in $Urls) {
        Write-V "Trying source: $url"
        try {
            Invoke-WebRequest -Uri $url -OutFile $Path -UseBasicParsing -TimeoutSec 600
        } catch {
            Remove-Item $Path -Force -ErrorAction SilentlyContinue
            continue
        }
        if (-not (Test-Path $Path)) { continue }
        $verdict = Test-FileChecksum $Path $Name
        if ($verdict -eq "bad") {
            Remove-Item $Path -Force -ErrorAction SilentlyContinue
            continue
        }
        return $true
    }
    return $false
}

# -- unified log helpers ----------------------------------------------------
$VerbosePref = ($env:NEBFLOW_VERBOSE -eq "1")
function Write-Info($m)  { Write-Host "[i] $m" }
function Write-Ok($m)    { Write-Host "[ok] $m" -ForegroundColor Green }
function Write-Warn2($m) { Write-Host "[warn] $m" -ForegroundColor Yellow }
function Write-Err2($m)  { Write-Host "[err] $m" -ForegroundColor Red }
function Write-V($m)     { if ($VerbosePref) { Write-Host "[v] $m" -ForegroundColor DarkGray } }
function Write-Stage($n, $total, $m) { Write-Host ""; Write-Host "==> [$n/$total] $m" -ForegroundColor Yellow }

# Parse flags
$Channel = if ($env:CHANNEL) { $env:CHANNEL } else { "stable" }
$Region = ""
# Also check command-line args (for direct execution, not via iex)
if ($args -contains "-Beta") { $Channel = "beta" }
if ($args -contains "--channel=beta") { $Channel = "beta" }
if ($args -contains "-VerboseFlag") { $VerbosePref = $true }
if ($args -contains "-Cn") { $Region = "cn" }
if ($args -contains "-Global") { $Region = "global" }

# Resolve version — COS version file (single source; GH API private 后不可用)
if ($Channel -eq "beta") {
    Write-Info "Resolving latest beta version..."
    if ($env:VERSION) {
        $Version = $env:VERSION
    } else {
        try {
            $BetaVersion = (Invoke-WebRequest -Uri "$CosBaseCn/latest-beta-version.txt" -UseBasicParsing -TimeoutSec 10).Content.Trim()
        } catch {}
        if (-not $BetaVersion) {
            Write-Err2 "Could not find a beta release (COS version file unreachable)."
            Write-Err2 "Check $CosBaseCn/latest-beta-version.txt"
            exit 10
        }
        $Version = $BetaVersion
    }
} else {
    Write-Info "Resolving latest stable version..."
    if ($env:VERSION) {
        $Version = $env:VERSION
    } else {
        try {
            $LatestVersion = (Invoke-WebRequest -Uri "$CosBaseCn/latest-version.txt" -UseBasicParsing -TimeoutSec 10).Content.Trim()
        } catch {}
        if (-not $LatestVersion) {
            Write-Err2 "Could not resolve latest version (COS version file unreachable)."
            Write-Err2 "Check $CosBaseCn/latest-version.txt"
            exit 10
        }
        $Version = $LatestVersion
    }
}
Write-V "Resolved VERSION=$Version (channel=$Channel)"

$InstallDir = if ($env:INSTALL_DIR) { $env:INSTALL_DIR } else { "$env:LOCALAPPDATA\$ProductName" }
$JarName = "$LowerName-assembly-$Version.jar"
$CosUrl = "$CosBaseCn/$JarName"

Write-Host ""
Write-Host "  $ProductName v$Version Installer ($Channel)" -ForegroundColor DarkGray
Write-Host ""

# --- [1/7] Java (floor 17; fresh installs get Temurin 21) ---
Write-Stage 1 7 "Checking Java..."

function Test-Java {
    $savedEAP = $ErrorActionPreference
    $ErrorActionPreference = "Continue"
    try {
        $output = & java -version 2>&1 | Out-String
        $match = [regex]::Match($output, '"(\d+)')
        if ($match.Success) {
            $ver = [int]$match.Groups[1].Value
            if ($ver -eq 1) {
                $match2 = [regex]::Match($output, '"1\.(\d+)')
                if ($match2.Success) { $ver = [int]$match2.Groups[1].Value }
            }
            if ($ver -ge $JdkMajorRequired) {
                $ErrorActionPreference = $savedEAP
                return $ver
            }
        }
    } catch {}
    # Fallback: check common install paths (17 = existing users, 21 = fresh installs)
    $jdkDirs = @(
        "C:\Program Files\Eclipse Adoptium\jdk-17*-hotspot\bin",
        "C:\Program Files\Eclipse Adoptium\jdk-21*-hotspot\bin",
        "C:\Program Files\Temurin\jdk-17*\bin",
        "C:\Program Files\Temurin\jdk-21*\bin",
        "C:\Program Files\Java\jdk-17*\bin",
        "C:\Program Files\Java\jdk-21*\bin"
    )
    foreach ($dir in $jdkDirs) {
        $javaExe = Get-Item (Join-Path $dir "java.exe") -ErrorAction SilentlyContinue | Select-Object -First 1
        if ($javaExe) {
            $output = & $javaExe.FullName -version 2>&1 | Out-String
            $match = [regex]::Match($output, '"(\d+)')
            if ($match.Success) {
                $ver = [int]$match.Groups[1].Value
                if ($ver -ge $JdkMajorRequired) {
                    # Add to PATH so subsequent commands find it
                    $env:Path = "$($javaExe.DirectoryName);$env:Path"
                    $ErrorActionPreference = $savedEAP
                    return $ver
                }
            }
        }
    }
    $ErrorActionPreference = $savedEAP
    return 0
}

$javaVer = Test-Java
if ($javaVer -ge $JdkMajorRequired) {
    $savedEAP = $ErrorActionPreference
    $ErrorActionPreference = "Continue"
    $javaLine = & java -version 2>&1 | Select-Object -First 1 | Out-String
    $ErrorActionPreference = $savedEAP
    Write-Ok "Java: $($javaLine.Trim())"
} else {
    Write-Info "Java $JdkMajorRequired+ not found. Installing OpenJDK 21..."

    $jdkInstalled = $false

    # Method 1: winget (cleanest if available)
    $wingetCmd = Get-Command winget -ErrorAction SilentlyContinue
    if ($wingetCmd) {
        Write-Info "Trying winget (EclipseAdoptium.Temurin.21.JDK)..."
        try {
            $proc = Start-Process winget -ArgumentList @(
                "install", "--id", "EclipseAdoptium.Temurin.21.JDK", "-e", "--source", "winget",
                "--silent", "--accept-package-agreements", "--accept-source-agreements"
            ) -Wait -PassThru -NoNewWindow 2>&1
            if ($LASTEXITCODE -eq 0) { $jdkInstalled = $true }
        } catch {}
    }

    # Method 2: direct Temurin 21 msi (COS mirror first, TUNA fallback)
    if (-not $jdkInstalled) {
        $jdkName = "OpenJDK21U-jdk_x64_windows_hotspot_21.0.12.1_1.msi"
        $jdkPath = "$env:TEMP\$jdkName"
        $jdkUrls = @(
            "$CosDepsBase/$jdkName",
            "https://mirrors.tuna.tsinghua.edu.cn/Adoptium/21/jdk/x64/windows/$jdkName"
        )
        Write-Info "Downloading Temurin JDK 21 msi (COS/TUNA)..."
        if (Get-FileFromSources -Path $jdkPath -Name $jdkName -Urls $jdkUrls) {
            Write-Info "Installing JDK 21..."
            $proc = Start-Process msiexec.exe -ArgumentList "/i", $jdkPath, "/quiet", "ADDLOCAL=FeatureMain,FeatureEnvironment,FeatureJarFileRunWith" -Wait -PassThru
            Remove-Item $jdkPath -Force -ErrorAction SilentlyContinue
            if ($proc.ExitCode -eq 0) { $jdkInstalled = $true }
            else { Write-Err2 "JDK msi install failed (exit code $($proc.ExitCode))." }
        } else {
            Write-Warn2 "JDK download failed from all sources."
        }
    }

    if (-not $jdkInstalled) {
        Write-Err2 "Manual install: https://adoptium.net/temurin/releases/?version=21 (Windows x64 msi)"
        Write-ChecksumHint "OpenJDK21U-jdk_x64_windows_hotspot_21.0.12.1_1.msi"
        Write-Err2 "Then re-run this installer."
        exit 11
    }

    # Refresh PATH in current session
    $env:Path = [Environment]::GetEnvironmentVariable("Path", "Machine") + ";" + [Environment]::GetEnvironmentVariable("Path", "User")

    $javaVer = Test-Java
    if ($javaVer -lt $JdkMajorRequired) {
        Write-Err2 "JDK installed but not detected. Please restart your terminal and run this script again."
        exit 11
    }
    Write-Ok "JDK 21 installed."
}

# --- [2/7] Git for Windows (provides bash.exe for Bash tool) ---
Write-Stage 2 7 "Checking Git for Windows..."

function Test-GitBash {
    $candidates = @(
        "$env:ProgramFiles\Git\bin\bash.exe",
        "${env:ProgramFiles(x86)}\Git\bin\bash.exe"
    )
    if ($env:LOCALAPPDATA) {
        $candidates += "$env:LOCALAPPDATA\Programs\Git\bin\bash.exe"
    }
    foreach ($path in $candidates) {
        if (Test-Path $path) { return $true }
    }
    # Check PATH but exclude WSL's bash (C:\Windows\System32\bash.exe)
    $bashCmd = Get-Command bash -ErrorAction SilentlyContinue
    if ($bashCmd -and $bashCmd.Source -notlike "*\System32\bash.exe") {
        return $true
    }
    return $false
}

if (Test-GitBash) {
    Write-Ok "Git Bash found"
} else {
    Write-Info "Git Bash not found. Installing Git for Windows..."

    $gitInstalled = $false

    # Method 1: Try winget (cleanest if available)
    $wingetCmd = Get-Command winget -ErrorAction SilentlyContinue
    if ($wingetCmd) {
        Write-Info "Trying winget..."
        try {
            $proc = Start-Process winget -ArgumentList @(
                "install", "--id", "Git.Git", "-e", "--source", "winget",
                "--silent", "--accept-package-agreements", "--accept-source-agreements"
            ) -Wait -PassThru -NoNewWindow 2>&1
            if ($LASTEXITCODE -eq 0 -and (Test-GitBash)) {
                $gitInstalled = $true
            }
        } catch {}
    }

    # Method 2: Direct download with region-aware source selection
    if (-not $gitInstalled) {
        # Determine region (timezone-based, instant - reused by JAR download later)
        if (-not $Region) {
            $tz = [TimeZoneInfo]::Local.Id
            if ($tz -match "China|Shanghai|Chongqing|Hong_Kong|Taipei|Macau|Urumqi") {
                $Region = "cn"
            } elseif ($env:LANG -match "zh_CN|zh_TW|zh_HK" -or $env:LC_ALL -match "zh_CN|zh_TW|zh_HK") {
                $Region = "cn"
            } else {
                $Region = "global"
            }
        }

        $gitVer = "2.55.0.3"
        $gitTag = "v2.55.0.windows.3"
        $gitInstaller = "Git-$gitVer-64-bit.exe"
        $gitPath = "$env:TEMP\$gitInstaller"

        # COS mirror is the primary source for every region (batch 2)
        if ($Region -eq "cn") {
            # China: COS, then domestic mirrors, GitHub last
            $gitMirrors = @(
                "$CosDepsBase/$gitInstaller",
                "https://registry.npmmirror.com/-/binary/git-for-windows/$gitTag/$gitInstaller",
                "https://ghproxy.net/https://github.com/git-for-windows/git/releases/download/$gitTag/$gitInstaller",
                "https://github.com/git-for-windows/git/releases/download/$gitTag/$gitInstaller"
            )
        } else {
            # Global: COS, then GitHub, domestic mirror fallback
            $gitMirrors = @(
                "$CosDepsBase/$gitInstaller",
                "https://github.com/git-for-windows/git/releases/download/$gitTag/$gitInstaller",
                "https://registry.npmmirror.com/-/binary/git-for-windows/$gitTag/$gitInstaller"
            )
        }

        Write-Info "Downloading Git for Windows..."
        if (Get-FileFromSources -Path $gitPath -Name $gitInstaller -Urls $gitMirrors) {
            Write-Info "Installing Git for Windows..."
            $proc = Start-Process $gitPath -ArgumentList "/VERYSILENT", "/NORESTART", "/NOCANCEL", "/SP-", "/CLOSEAPPLICATIONS", "/RESTARTAPPLICATIONS" -Wait -PassThru
            Remove-Item $gitPath -Force -ErrorAction SilentlyContinue

            # Refresh PATH so subsequent checks find bash
            $env:Path = [Environment]::GetEnvironmentVariable("Path", "Machine") + ";" + [Environment]::GetEnvironmentVariable("Path", "User")

            if ($proc.ExitCode -eq 0 -and (Test-GitBash)) {
                Write-Ok "Git for Windows installed."
            } else {
                Write-Err2 "Git install may have failed (exit $($proc.ExitCode))."
                Write-Warn2 "Please install manually: https://git-scm.com/download/win"
            }
        } else {
            Write-Err2 "Git download failed from all sources."
            Write-Warn2 "Please install manually: https://git-scm.com/download/win"
            Write-Warn2 "(Bash tool requires Git for Windows)"
            Write-ChecksumHint $gitInstaller
        }
    }
}

# --- [3/7] Download $ProductName ---
Write-Stage 3 7 "Downloading $ProductName v$Version..."

New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
$jarPath = Join-Path $InstallDir $JarName

if (Test-Path $jarPath) {
    Write-Ok "Already up-to-date (v$Version)."
} else {
    # Clean up old versions (keep .nebflow user data untouched)
    $oldJars = @(Get-ChildItem (Join-Path $InstallDir "$LowerName-assembly-*.jar") -ErrorAction SilentlyContinue) + @(Get-ChildItem (Join-Path $InstallDir "nebflow-assembly-*.jar") -ErrorAction SilentlyContinue)
    foreach ($old in $oldJars) {
        if ($old.FullName -ne $jarPath) {
            Remove-Item $old.FullName -Force -ErrorAction SilentlyContinue
            Write-V "Removed old: $($old.Name)"
        }
    }

    # Auto-detect region for download source selection
    if (-not $Region) {
        $tz = [TimeZoneInfo]::Local.Id
        if ($tz -match "China|Shanghai|Chongqing|Hong_Kong|Taipei|Macau|Urumqi") {
            $Region = "cn"
        } elseif ($env:LANG -match "zh_CN|zh_TW|zh_HK" -or $env:LC_ALL -match "zh_CN|zh_TW|zh_HK") {
            $Region = "cn"
        } else {
            # Quick connectivity test: compare latency
            try {
                $cosTime = (Measure-Command {
                    Invoke-WebRequest -Uri "$CosBaseCn/" -UseBasicParsing -TimeoutSec 3 | Out-Null
                }).TotalMilliseconds
            } catch { $cosTime = 9999 }
            try {
                $ghTime = (Measure-Command {
                    Invoke-WebRequest -Uri "https://github.com/favicon.ico" -UseBasicParsing -TimeoutSec 3 | Out-Null
                }).TotalMilliseconds
            } catch { $ghTime = 9999 }
            if ($cosTime -lt 500 -and $cosTime -lt ($ghTime / 2)) {
                $Region = "cn"
            } else {
                $Region = "global"
            }
        }
    }
    Write-Info "Region: $Region (use -Cn or -Global to override)"

    # #29: 仓库 private 后 GitHub Releases 未认证 404——COS 单一源
    try {
        Invoke-WebRequest -Uri $CosUrl -OutFile $jarPath -UseBasicParsing -TimeoutSec 600
    } catch {
        Write-Err2 "Download failed from COS. Check $CosUrl"
        exit 12
    }
    $size = [math]::Round((Get-Item $jarPath).Length / 1MB, 1)
    Write-Ok "Downloaded $JarName from COS ($size MB)."
}

# --- [4/7] ripgrep (rg) for search support ---
Write-Stage 4 7 "Installing ripgrep (rg)..."
if (Get-Command "rg" -ErrorAction SilentlyContinue) {
    Write-Ok "rg already available in PATH."
} elseif (Test-Path (Join-Path $InstallDir "rg.exe")) {
    Write-Ok "rg already cached."
} else {
    $rgName = "ripgrep-$RgVersion-x86_64-pc-windows-msvc.zip"
    $rgZip = Join-Path $InstallDir "rg.zip"
    try {
        Write-Info "Downloading rg $RgVersion..."
        $rgUrls = @(
            "$CosDepsBase/$rgName",
            "https://github.com/BurntSushi/ripgrep/releases/download/$RgVersion/$rgName",
            "https://ghproxy.net/https://github.com/BurntSushi/ripgrep/releases/download/$RgVersion/$rgName"
        )
        if (-not (Get-FileFromSources -Path $rgZip -Name $rgName -Urls $rgUrls)) {
            throw "all sources failed"
        }
        Add-Type -AssemblyName System.IO.Compression.FileSystem
        $zip = [System.IO.Compression.ZipFile]::OpenRead($rgZip)
        $entry = $zip.Entries | Where-Object { $_.Name -eq "rg.exe" } | Select-Object -First 1
        if ($entry) {
            [System.IO.Compression.ZipFileExtensions]::ExtractToFile($entry, (Join-Path $InstallDir "rg.exe"), $true)
            Write-Ok "rg installed to $InstallDir"
        }
        $zip.Dispose()
        Remove-Item $rgZip -Force -ErrorAction SilentlyContinue
    } catch {
        Write-Warn2 "rg download failed: $_"
        Write-Warn2 "Search will rely on PATH install."
        Write-Warn2 "Manual download: https://github.com/BurntSushi/ripgrep/releases/tag/v$RgVersion"
        Write-Warn2 "Manual placement: extract rg.exe to $InstallDir\rg.exe"
        Write-ChecksumHint $rgName
    }
}

# --- [5/7] Whisper voice model (best-effort) ---
Write-Stage 5 7 "Voice model (Whisper, ~75MB one-time)..."
$modelDir = Join-Path $env:USERPROFILE "$HomeDir\voice-models\onnx-community\whisper-base"
$onnxEncPath = Join-Path $modelDir "onnx\encoder_model_quantized.onnx"

if (Test-Path $onnxEncPath) {
    Write-V "Already installed."
} else {
    # Determine mirror
    if (-not $Region) { $Region = "global" }
    $hfBase = if ($Region -eq "cn") {
        "https://hf-mirror.com/onnx-community/whisper-base/resolve/main"
    } else {
        "https://huggingface.co/onnx-community/whisper-base/resolve/main"
    }

    New-Item -ItemType Directory -Force -Path (Join-Path $modelDir "onnx") | Out-Null

    # Download config files (small)
    $configFiles = @("config.json", "tokenizer.json", "generation_config.json", "preprocessor_config.json")
    foreach ($cf in $configFiles) {
        $target = Join-Path $modelDir $cf
        if (-not (Test-Path $target)) {
            try { Invoke-WebRequest -Uri "$hfBase/$cf" -OutFile $target -UseBasicParsing -TimeoutSec 15 } catch {}
        }
    }

    # Download quantized ONNX models (encoder ~22MB + decoder ~51MB)
    Write-Info "Downloading model..."
    $dlOk = $true
    try {
        Invoke-WebRequest -Uri "$hfBase/onnx/encoder_model_quantized.onnx" -OutFile $onnxEncPath -UseBasicParsing -TimeoutSec 120
    } catch { $dlOk = $false }
    try {
        $decPath = Join-Path $modelDir "onnx\decoder_model_merged_quantized.onnx"
        Invoke-WebRequest -Uri "$hfBase/onnx/decoder_model_merged_quantized.onnx" -OutFile $decPath -UseBasicParsing -TimeoutSec 120
    } catch { $dlOk = $false }
    if ($dlOk) {
        Write-Ok "Voice model installed."
    } else {
        Write-Warn2 "Download failed (voice will use CDN on first use)."
    }
}

# --- [6/7] Create wrapper scripts ---
Write-Stage 6 7 "Creating launcher..."

# PowerShell wrapper
$wrapperPath = Join-Path $InstallDir "$WrapperName.ps1"
$wrapperContent = @"
`$jar = @(Get-ChildItem "`$PSScriptRoot\$LowerName-assembly-*.jar") + @(Get-ChildItem "`$PSScriptRoot\nebflow-assembly-*.jar") | Sort-Object Name | Select-Object -Last 1
if (-not `$jar) {
    Write-Host "ERROR: $ProductName JAR not found in `$PSScriptRoot" -ForegroundColor Red
    exit 1
}
& java --add-opens java.base/java.lang=ALL-UNNAMED -jar `$jar.FullName `$args
"@
Set-Content -Path $wrapperPath -Value $wrapperContent -Encoding UTF8
Write-Ok "Wrapper created: $wrapperPath"

# CMD wrapper
$cmdPath = Join-Path $InstallDir "$WrapperName.cmd"
$cmdContent = @"
@echo off
set "PATH=%PATH%;C:\Program Files\Eclipse Adoptium\jdk-21.0.12.1-hotspot\bin;C:\Program Files\Eclipse Adoptium\jdk-17.0.19.10-hotspot\bin"
for %%f in ("%~dp0nebflow-assembly-*.jar" "%~dp0$LowerName-assembly-*.jar") do set JAR=%%f
if "%JAR%"=="" (
    echo ERROR: %~dp0 JAR not found
    exit /b 1
)
java --add-opens java.base/java.lang=ALL-UNNAMED -jar "%JAR%" %*
"@
Set-Content -Path $cmdPath -Value $cmdContent -Encoding ASCII

# Add to PATH
$userPath = [Environment]::GetEnvironmentVariable("Path", "User")
if ($userPath -notlike "*$InstallDir*") {
    [Environment]::SetEnvironmentVariable("Path", "$userPath;$InstallDir", "User")
    Write-Ok "Added to PATH"
}

# --- [7/7] Config + install manifest ---
Write-Stage 7 7 "Setting up config..."

$configDir = Join-Path $env:USERPROFILE "$HomeDir"
$configFile = Join-Path $configDir "$ConfigFile"
if (-not (Test-Path $configFile)) {
    New-Item -ItemType Directory -Force -Path $configDir | Out-Null
    $configContent = "{}"
    [System.IO.File]::WriteAllText($configFile, $configContent)
    Write-Ok "Config created: $configFile"
    Write-Warn2 "Please edit it to set your API key."
} else {
    Write-V "Config already exists."
}

# Installer manifest (ScriptVersion + environment) for `nebflow update`
# and diagnostics. Overwritten on each (re)install.
if (-not $Region) { $Region = "global" }
$manifestPath = Join-Path $configDir "install-manifest.json"
$manifest = @"
{
  "scriptVersion": "$ScriptVersion",
  "product": "$ProductName",
  "version": "$Version",
  "channel": "$Channel",
  "region": "$Region",
  "os": "windows",
  "arch": "x64",
  "installDir": "$($InstallDir.Replace('\', '\\'))",
  "installedAt": "$((Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ'))"
}
"@
[System.IO.File]::WriteAllText($manifestPath, $manifest)
Write-V "Manifest written: $manifestPath"

# --- Done ---
Write-Host ""
Write-Host "[ok] $ProductName v$Version installed!" -ForegroundColor Green
Write-Host ""
Write-Host "  Commands:" -ForegroundColor White
Write-Host "    $WrapperName --help" -ForegroundColor Cyan
Write-Host "    $WrapperName start" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Config: $env:USERPROFILE\$HomeDir\$ConfigFile" -ForegroundColor DarkGray
Write-Host ""
Write-Host "  NOTE: Restart your terminal for PATH to take effect." -ForegroundColor Yellow
Write-Host ""
if ([Console]::IsInputRedirected -eq $false) {
    Read-Host "Press Enter to exit"
}