#!/bin/bash
set -e

# Nebflow cross-platform installer (macOS / Linux) — script v2
# ---------------------------------------------------------------
# SCRIPT_VERSION : installer version (written into the local install
#                  manifest for `nebflow update` and diagnostics).
# Pipeline       : [1/6] env detect -> [2/6] deps (curl/JDK/rg/voice) ->
#                  [3/6] jar -> [4/6] wrapper+PATH -> [5/6] config ->
#                  [6/6] done.
# Idempotent     : safe to re-run; installed/satisfied deps are detected
#                  and skipped.
# Flags          : --beta | --channel=beta | --cn | --global | --verbose
#                  (curl|bash pipe: env CHANNEL=beta / REGION=cn /
#                  NEBFLOW_VERBOSE=1)
# Exit codes     : 0 ok | 10 version resolve | 11 java install |
#                  12 jar download | 13 no curl/wget
# ---------------------------------------------------------------

# -- Brand values (L2 rebrand): rendered from repo-root brand.conf at -------
# -- release time (scripts/render-brand.sh); do not edit by hand. -----------
# The runtime dual-reads legacy names (L3), so rendering NEW values here
# keeps existing user data working - old dirs/env/config fall back.
PRODUCT_NAME=Nebflow
LOWER_NAME=nebflow
COS_BUCKET=nebflow-releases-1411212853
HOME_DIR=.nebflow
CONFIG_FILE=nebflow.json
WRAPPER_NAME=nebflow
COS_BASE_CN="https://${COS_BUCKET}.cos.ap-nanjing.myqcloud.com"
# Batch 2 (v2): all third-party deps mirrored on COS under the deps/ prefix
# (single primary source for every region; upstream sources demoted to
# fallback). Integrity via deps/checksums.txt (sha256, generated by
# scripts/upload-deps.sh at upload time).
COS_DEPS_BASE="${COS_BASE_CN}/deps"
# 仓库已转 private（#29，2026-09-01）：GitHub Releases 未认证下载 404——
# Nebflow jar 下载/版本解析统一走 COS（单一源）。第三方依赖
# （Homebrew/ripgrep/HuggingFace 模型/favicon 连通性测试）
# 与仓库 private 无关，仍走各自公共源。

SCRIPT_VERSION="2.0.0"
RG_VERSION="14.1.1"
JDK_MAJOR_REQUIRED=17   # runtime floor; fresh installs target OpenJDK 21
ERR_VERSION=10
ERR_JAVA=11
ERR_JAR=12
ERR_CURL=13

# -- unified log helpers ----------------------------------------------------
VERBOSE="${NEBFLOW_VERBOSE:-0}"
log_i()    { echo "[i] $*"; }
log_ok()   { echo "[ok] $*"; }
log_warn() { echo "[warn] $*"; }
log_err()  { echo "[err] $*" >&2; }
log_v()    { [ "$VERBOSE" = "1" ] && echo "[v] $*" || true; }
stage_hdr(){ echo ""; echo "==> [$1/6] $2"; }

# Parse flags
CHANNEL="stable"
for arg in "$@"; do
    case "$arg" in
        --beta|--channel=beta) CHANNEL="beta" ;;
        --cn) REGION="cn" ;;
        --global) REGION="global" ;;
        --verbose) VERBOSE=1 ;;
    esac
done

# Resolve version — COS version file (single source; GH API private 后不可用)
resolve_version() {
    if [ "$CHANNEL" = "beta" ]; then
        log_i "Resolving latest beta version..."
        if [ -z "$VERSION" ]; then
            BETA_TAG=$(curl -fsSL --connect-timeout 5 --max-time 10 \
                "${COS_BASE_CN}/latest-beta-version.txt" 2>/dev/null || true)
            if [ -z "$BETA_TAG" ]; then
                log_err "Could not find a beta release (COS version file unreachable)."
                log_err "Check ${COS_BASE_CN}/latest-beta-version.txt"
                exit $ERR_VERSION
            fi
            VERSION="$BETA_TAG"
        fi
    else
        log_i "Resolving latest stable version..."
        if [ -z "$VERSION" ]; then
            LATEST_VERSION=$(curl -fsSL --connect-timeout 5 --max-time 10 \
                "${COS_BASE_CN}/latest-version.txt" 2>/dev/null || true)
            if [ -z "$LATEST_VERSION" ]; then
                log_err "Could not resolve latest version (COS version file unreachable)."
                log_err "Check ${COS_BASE_CN}/latest-version.txt"
                exit $ERR_VERSION
            fi
            VERSION="$LATEST_VERSION"
        fi
    fi
    log_v "Resolved VERSION=${VERSION} (channel=${CHANNEL})"
}

INSTALL_DIR="${INSTALL_DIR:-${HOME}/${HOME_DIR}/bin}"

# >>> BRAND-UI-BEGIN (batch 4 redesign: pixel logo + progress bar) >>>
# Brand banner: the Nebflow 7x7 pixel logo rendered as terminal color
# blocks. The matrix was sampled OFFLINE from the brand assets
# (docs/Nebflow/assets/logo/{dark,bright}.png, 224x224 = a 7x7 grid of 32px
# cells, cell-center NEAREST sampling - the same pixelated look as the web
# UI's image-rendering: pixelated) and embedded here as constant data: zero
# image files, zero python, zero network at runtime. Full untrimmed 7x7
# matrix (author ruling 2026-09-06: no 5x6 cropping - keeps the source
# aspect); G = brand green #07C160, W = white (dark terminals) or
# black (light terminals). No ASCII-art/figlet wordmark: the logo blocks
# carry the brand, the wordmark is plain lowercase text.
#
# Color degrade chain: truecolor (3) -> xterm-256 (2) -> 8-color (1) ->
# mono # mask (0), every level keeps the shape intact. Width discipline
# (author ruling 2026-09-06, revised same-day): ONE pixel = TWO character
# cells at every level - a terminal glyph is ~2x taller than wide, so each
# pixel spans 2 columns and the logo keeps its source aspect. Mono renders
# "##" per pixel, color levels render a 2-column background block, empty
# pixels are 2 plain spaces; adjacent solid pixels touch with no gap
# (e.g. mask row "GG.WWW." -> "####  ######  ", 14 columns per logo row).
#   guards: NO_COLOR / CI / non-TTY / TERM=dumb -> mono (plain text)
#   theme : NEBFLOW_BANNER_THEME=dark|light overrides; else COLORFGBG's
#           background field (>=7 means a light background); default dark
#   level : NEBFLOW_UI_LEVEL=0..3 forces a level (preview/testing)

BANNER_MASK=(
    "......."
    "GG.WWW."
    "GG.WWW."
    "..W..W."
    "..W..W."
    "..W..W."
    "......."
)

_ui_level=0
_ui_theme="dark"
_ui_utf8=0
case "${LC_ALL:-${LC_CTYPE:-${LANG:-}}}" in
    *UTF-8*|*utf8*|*utf-8*) _ui_utf8=1 ;;
esac

ui_detect() {
    case "${NEBFLOW_UI_LEVEL:-}" in
        0|1|2|3) _ui_level="${NEBFLOW_UI_LEVEL}" ;;
        *)
            _ui_level=0
            if [ -t 1 ] && [ -z "${NO_COLOR:-}" ] && [ -z "${CI:-}" ] && [ "${TERM:-dumb}" != "dumb" ]; then
                case "${COLORTERM:-}" in
                    truecolor|24bit) _ui_level=3 ;;
                    *) case "${TERM:-}" in
                           *256color*) _ui_level=2 ;;
                           *)         _ui_level=1 ;;
                       esac ;;
                esac
            fi
            ;;
    esac
    case "${NEBFLOW_BANNER_THEME:-}" in
        dark|light) _ui_theme="${NEBFLOW_BANNER_THEME}" ;;
        *)
            _ui_theme="dark"
            if [ -n "${COLORFGBG:-}" ]; then
                local _bg="${COLORFGBG##*;}"
                case "$_bg" in
                    ''|*[!0-9]*) : ;;
                    *) [ "$_bg" -ge 7 ] 2>/dev/null && _ui_theme="light" ;;
                esac
            fi
            ;;
    esac
}

# -- low-level painters -------------------------------------------------------
# One logo pixel = TWO character cells at every color level (author ruling
# 2026-09-06, revised): "##" in mono, a 2-column bg block in color levels;
# transparent pixels are two plain spaces. Adjacent solid pixels connect
# with no separator.
_px() {  # <G|W|.>
    case "$1" in
        .) printf '  '; return 0 ;;
    esac
    case "$_ui_level" in
        3)
            if [ "$1" = "G" ]; then printf '\033[48;2;7;193;96m  \033[0m'
            elif [ "$_ui_theme" = "dark" ]; then printf '\033[48;2;255;255;255m  \033[0m'
            else printf '\033[48;2;0;0;0m  \033[0m'; fi
            ;;
        2)  # nearest xterm-256: #07C160 -> 35 (#00af5f); white 231; black 16
            if [ "$1" = "G" ]; then printf '\033[48;5;35m  \033[0m'
            elif [ "$_ui_theme" = "dark" ]; then printf '\033[48;5;231m  \033[0m'
            else printf '\033[48;5;16m  \033[0m'; fi
            ;;
        1)
            if [ "$1" = "G" ]; then printf '\033[42m  \033[0m'
            elif [ "$_ui_theme" = "dark" ]; then printf '\033[47m  \033[0m'
            else printf '\033[40m  \033[0m'; fi
            ;;
        *)  printf '##' ;;
    esac
}

_fg_green() {
    case "$_ui_level" in
        3) printf '\033[1;38;2;7;193;96m' ;;
        2) printf '\033[1;38;5;35m' ;;
        1) printf '\033[1;32m' ;;
    esac
}
_dim() { [ "$_ui_level" -ge 1 ] && printf '\033[2m' || true; }
_rst() { [ "$_ui_level" -ge 1 ] && printf '\033[0m' || true; }

print_banner() {
    ui_detect
    printf '\n'
    local _i _j _row
    for _i in 0 1 2 3 4 5 6; do
        _row="${BANNER_MASK[$_i]}"
        printf '  '
        for ((_j=0; _j<${#_row}; _j++)); do _px "${_row:$_j:1}"; done
        case "$_i" in
            2) printf '  '; _fg_green; printf '%s' "${LOWER_NAME}"; _rst ;;
            3) printf '  '; _dim; printf 'v%s installer (%s)' "${VERSION:-dev}" "${CHANNEL}"; _rst ;;
        esac
        printf '\n'
    done
    printf '\n'
}

# -- download progress --------------------------------------------------------
# Clean single-line bar in brand green: percentage only when content-length
# is known (unknown length -> spinner + byte count, never a fake %), current
# file label, size/speed. In-place \r redraw, COLUMNS-adaptive. Non-TTY
# (curl|bash pipe) / TERM=dumb: no control output at all, plain log lines.

_progress_ok() {
    [ -t 1 ] && [ "${TERM:-dumb}" != "dumb" ] && command -v curl > /dev/null 2>&1
}

_fmt_bytes() {  # <bytes> -> "12.3M" / "640K" / "512B"
    awk -v b="${1:-0}" 'BEGIN{
        if (b >= 1048576) printf "%.1fM", b/1048576;
        else if (b >= 1024) printf "%.0fK", b/1024;
        else printf "%dB", b;
    }'
}

_bar() {  # <done> <total|-1> <width> -> bar body (no newline)
    local _done=$1 _total=$2 _w=$3
    local _e=0 _filled=0 _frac=0 _i _out=""
    if [ "$_total" -gt 0 ] 2>/dev/null; then
        _e=$(( _done * _w * 8 / _total ))
        [ "$_e" -gt $((_w*8)) ] && _e=$((_w*8))
        _filled=$((_e/8)); _frac=$((_e%8))
    fi
    local _g="" _r="" _d=""
    case "$_ui_level" in
        3) _g=$'\033[38;2;7;193;96m' ;;
        2) _g=$'\033[38;5;35m' ;;
        1) _g=$'\033[32m' ;;
    esac
    if [ -n "$_g" ]; then _r=$'\033[0m'; _d=$'\033[2m'; fi
    _out="$_g"
    if [ "$_ui_utf8" = 1 ]; then
        # eighth-block partials give sub-cell precision
        local _parts=("" "▏" "▎" "▍" "▌" "▋" "▊" "▉")
        for ((_i=0; _i<_filled; _i++)); do _out="${_out}█"; done
        if [ "$_frac" -gt 0 ]; then _out="${_out}${_parts[$_frac]}"; _filled=$((_filled+1)); fi
        _out="${_out}${_r}${_d}"
        for ((_i=_filled; _i<_w; _i++)); do _out="${_out}░"; done
    else
        for ((_i=0; _i<_filled; _i++)); do _out="${_out}#"; done
        if [ "$_frac" -gt 0 ]; then _out="${_out}>"; _filled=$((_filled+1)); fi
        _out="${_out}${_r}"
        for ((_i=_filled; _i<_w; _i++)); do _out="${_out}-"; done
    fi
    _out="${_out}${_r}"
    printf '%s' "$_out"
}

# Compose one full progress line (colors included). Pure function of its
# arguments - also driven by scripts/preview-brand-ui.sh for static frames.
_progress_line() {  # <done> <total|-1> <label> <speed_Bps|-1> <spin_idx>
    local _done=$1 _total=$2 _label=$3 _spd=$4 _spin=$5
    local _cols=${COLUMNS:-80}
    local _info=" $(_fmt_bytes "$_done")"
    [ "$_total" -gt 0 ] 2>/dev/null && _info="${_info}/$(_fmt_bytes "$_total")"
    [ "$_spd" -ge 0 ] 2>/dev/null && _info="${_info}  $(_fmt_bytes "$_spd")/s"
    local _pct
    if [ "$_total" -gt 0 ] 2>/dev/null; then
        _pct=$(awk -v d="$_done" -v t="$_total" 'BEGIN{p=int(d*100/t); printf "%3d%%", (p>100?100:p)}')
    else
        local _s='|/-\'
        _pct="  ${_s:$((_spin % 4)):1} "
    fi
    local _w=$(( _cols - ${#_label} - ${#_info} - 16 ))
    [ "$_w" -lt 10 ] && _w=10
    [ "$_w" -gt 48 ] && _w=48
    printf '  %s %s%s  %s' "$_pct" "$(_bar "$_done" "$_total" "$_w")" "$_info" "$_label"
}

progress_render() {  # <done> <total|-1> <label> <speed_Bps|-1> <spin_idx>
    _progress_ok || return 0
    printf '\r\033[K%s' "$(_progress_line "$@")"
}
# <<< BRAND-UI-END <<<

# ---- [1/6] environment ----------------------------------------------------
detect_os() {
    local uname_out="$(uname -s 2>/dev/null)"
    case "$uname_out" in
        Darwin*) OS_FAMILY="mac" ;;
        Linux*)  OS_FAMILY="linux" ;;
        MINGW*|MSYS*|CYGWIN*) OS_FAMILY="windows" ;;
        *)       OS_FAMILY="unknown" ;;
    esac
}

detect_arch() {
    case "$(uname -m)" in
        arm64|aarch64) ARCH="arm64" ;;
        *)             ARCH="x64" ;;
    esac
}

# Auto-detect region: check if user is in China
detect_region() {
    if [ -n "$REGION" ]; then
        return 0  # already set by --cn or --global flag
    fi
    # Method 1: check system timezone
    local tz=""
    if [ -f /etc/timezone ]; then
        tz=$(cat /etc/timezone 2>/dev/null)
    elif command -v timedatectl &> /dev/null; then
        tz=$(timedatectl show -p Timezone 2>/dev/null | cut -d= -f2)
    fi
    case "$tz" in
        Asia/Shanghai|Asia/Chongqing|Asia/Hong_Kong|Asia/Taipei|Asia/Macau|PRC|Asia/Urumqi)
            REGION="cn"
            return 0
            ;;
    esac

    # Method 2: check LANG/LC_ALL for zh_CN
    case "${LANG:-}${LC_ALL:-}" in
        *zh_CN*|*zh_TW*|*zh_HK*)
            REGION="cn"
            return 0
            ;;
    esac

    # Method 3: try a quick connectivity test (COS is fast in China, slow elsewhere)
    # Test latency to COS vs GitHub — pick whichever responds first
    local cos_ms=99999 gh_ms=99999
    if command -v curl &> /dev/null; then
        cos_ms=$(curl -o /dev/null -s -w '%{time_total}' --connect-timeout 2 --max-time 3 \
            "${COS_BASE_CN}/" 2>/dev/null | \
            awk '{printf "%d", $1 * 1000}')
        gh_ms=$(curl -o /dev/null -s -w '%{time_total}' --connect-timeout 2 --max-time 3 \
            "https://github.com/favicon.ico" 2>/dev/null | \
            awk '{printf "%d", $1 * 1000}')
    fi

    # If COS is significantly faster (> 2x), user is likely in China
    if [ "$cos_ms" -lt 500 ] && [ "$cos_ms" -lt $((gh_ms / 2)) ]; then
        REGION="cn"
    else
        REGION="global"
    fi
}

detect_pkg_mgr() {
    PKG_MGR=""
    local m
    for m in apt-get dnf yum apk; do
        if command -v "$m" > /dev/null 2>&1; then PKG_MGR="$m"; break; fi
    done
    if [ -n "$PKG_MGR" ]; then
        log_i "Package manager: ${PKG_MGR}"
    else
        log_v "No known package manager found (apt/dnf/yum/apk)"
    fi
}

stage_env() {
    stage_hdr 1 "Checking environment..."
    detect_os
    detect_arch
    log_i "OS: ${OS_FAMILY} (${ARCH})"
    if [ "$OS_FAMILY" = "unknown" ]; then
        log_err "Unsupported platform: $(uname -s 2>/dev/null || echo unknown)"
        exit 1
    fi
    if [ "$OS_FAMILY" = "windows" ]; then
        log_err "Windows detected - use install.ps1 (PowerShell) instead of install.sh."
        exit 1
    fi
    detect_region
    log_i "Region: ${REGION} (use --cn or --global to override)"
    if [ "$OS_FAMILY" = "linux" ]; then
        detect_pkg_mgr
    fi
}

# ---- [2/6] dependencies ---------------------------------------------------

_java_ok() {
    command -v java &> /dev/null || return 1
    local v
    v=$(java -version 2>&1 | awk -F '"' '/version/ {print $2}' | cut -d'.' -f1)
    [ "$v" = "1" ] && v=$(java -version 2>&1 | awk -F '"' '/version/ {print $2}' | cut -d'.' -f2)
    [ "$v" -ge "$JDK_MAJOR_REQUIRED" ] 2>/dev/null
}

java_manual_hint() {
    log_err "Manual install: https://adoptium.net/temurin/releases/?version=21"
    log_err "Then re-run this installer."
}

# Region-gated Homebrew mirror combo (cn): the mirror installer only solves
# step 1 (bootstrap); brew's own git repos must also point at the TUNA
# mirror, and the bottle domain redirects package payloads. All three are
# environment variables consumed by brew at runtime.
configure_homebrew_mirrors() {
    if [ "$REGION" = "cn" ]; then
        export HOMEBREW_BREW_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git"
        export HOMEBREW_CORE_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git"
        export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles"
        log_v "Homebrew cn mirrors set (brew/core git remotes + bottle domain: TUNA)"
    fi
}

ensure_brew() {
    command -v brew > /dev/null 2>&1 && return 0
    log_i "Homebrew not found. Installing..."
    # Xcode CLT is a Homebrew prerequisite; trigger it if absent
    if ! xcode-select -p > /dev/null 2>&1; then
        log_warn "Xcode Command Line Tools missing - triggering install (a dialog may appear; re-run this script after it finishes)."
        xcode-select --install > /dev/null 2>&1 || true
    fi
    configure_homebrew_mirrors
    local installer_done=0
    local tmp_installer
    tmp_installer=$(mktemp /tmp/${LOWER_NAME}-brew-install-XXXXXX.sh)
    if [ "$REGION" = "cn" ]; then
        # 1) COS snapshot of the installer (batch 2) - no GitHub dependency
        log_i "Fetching Homebrew installer from COS mirror (cn)..."
        if curl -fsSL --connect-timeout 8 --max-time 30 \
            "${COS_DEPS_BASE}/homebrew-install.sh" -o "$tmp_installer" 2>/dev/null; then
            if bash "$tmp_installer"; then installer_done=1; fi
        fi
        # 2) TUNA git mirror of the installer repo
        if [ "$installer_done" = "0" ] && command -v git > /dev/null 2>&1; then
            log_i "Fetching Homebrew installer from TUNA mirror (cn)..."
            rm -rf /tmp/${LOWER_NAME}-homebrew-install
            if git clone --depth 1 https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/install.git \
                /tmp/${LOWER_NAME}-homebrew-install > /dev/null 2>&1; then
                if bash /tmp/${LOWER_NAME}-homebrew-install/install.sh; then installer_done=1; fi
                rm -rf /tmp/${LOWER_NAME}-homebrew-install
            fi
        fi
    fi
    rm -f "$tmp_installer"
    # 3) Official installer (raw.githubusercontent.com; needs overseas access)
    if [ "$installer_done" = "0" ]; then
        log_i "Fetching official Homebrew installer..."
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" || return 1
    fi
    # Make brew visible in this session (Apple Silicon vs Intel prefix)
    if [ -x /opt/homebrew/bin/brew ]; then
        eval "$(/opt/homebrew/bin/brew shellenv)" 2>/dev/null || export PATH="/opt/homebrew/bin:$PATH"
    elif [ -x /usr/local/bin/brew ]; then
        eval "$(/usr/local/bin/brew shellenv)" 2>/dev/null || export PATH="/usr/local/bin:$PATH"
    fi
    command -v brew > /dev/null 2>&1
}

link_brew_jdk() {
    # brew openjdk@21 needs a symlink into /Library/Java/JavaVirtualMachines
    local prefix
    if [ -d "/opt/homebrew/opt/openjdk@21" ]; then
        prefix="/opt/homebrew"
    elif [ -d "/usr/local/opt/openjdk@21" ]; then
        prefix="/usr/local"
    else
        return 0
    fi
    sudo ln -sfn "${prefix}/opt/openjdk@21/libexec/openjdk.jdk" \
        /Library/Java/JavaVirtualMachines/openjdk-21.jdk 2>/dev/null || true
    export PATH="${prefix}/opt/openjdk@21/bin:$PATH"
}

ensure_java_mac() {
    ensure_brew || {
        log_err "Could not install Homebrew; cannot install JDK automatically."
        java_manual_hint
        exit $ERR_JAVA
    }
    log_i "Installing OpenJDK 21 via Homebrew..."
    if ! brew install --quiet openjdk@21; then
        log_err "brew install openjdk@21 failed."
        java_manual_hint
        exit $ERR_JAVA
    fi
    link_brew_jdk
}

ensure_java_linux_tarball() {
    # Fallback when distro packages are unavailable/failed:
    # 1) COS-mirrored Temurin 21 tarball (domestic-friendly)
    # 2) Adoptium API (overseas last resort)
    local jdk_arch="x64"
    [ "$ARCH" = "arm64" ] && jdk_arch="aarch64"
    local jdk_ver="21.0.12.1_1"
    local tarball_name="OpenJDK21U-jdk_${jdk_arch}_linux_hotspot_${jdk_ver}.tar.gz"
    local jdk_dir="${HOME}/${HOME_DIR}/jdk-21"
    mkdir -p "${HOME}/${HOME_DIR}"
    local tmp_tar
    tmp_tar=$(mktemp /tmp/${LOWER_NAME}-jdk-XXXXXX.tar.gz)
    local jdk_url="https://api.adoptium.net/v3/binary/latest/21/ga/linux/${jdk_arch}/jdk/hotspot/normal/eclipse"
    if download_file "$tmp_tar" "$tarball_name" "$tarball_name" \
        "${COS_DEPS_BASE}/${tarball_name}" "$jdk_url"; then
        tar xzf "$tmp_tar" -C "${HOME}/${HOME_DIR}" 2>/dev/null
        rm -f "$tmp_tar"
        local extracted
        extracted=$(ls -d "${HOME}"/${HOME_DIR}/jdk-21* 2>/dev/null | head -1)
        if [ -n "$extracted" ]; then
            mv "$extracted" "$jdk_dir" 2>/dev/null || true
            export PATH="$jdk_dir/bin:$PATH"
            export JAVA_HOME="$jdk_dir"
            return 0
        fi
    else
        rm -f "$tmp_tar"
    fi
    return 1
}

ensure_java_linux() {
    local installed_any=0
    case "$PKG_MGR" in
        apt-get)
            log_i "Installing OpenJDK 21 via apt..."
            sudo apt-get update -qq && sudo apt-get install -y openjdk-21-jdk-headless 2>&1 || true
            installed_any=1
            ;;
        dnf)
            log_i "Installing OpenJDK 21 via dnf..."
            sudo dnf install -y java-21-openjdk-devel 2>&1 || true
            installed_any=1
            ;;
        yum)
            log_i "Installing OpenJDK 21 via yum..."
            sudo yum install -y java-21-openjdk-devel 2>&1 || true
            installed_any=1
            ;;
        apk)
            log_i "Installing OpenJDK 21 via apk..."
            sudo apk add --no-cache openjdk21 2>&1 || true
            installed_any=1
            ;;
    esac
    log_v "pkg-mgr install attempted=${installed_any}"
    if ! _java_ok; then
        log_i "Package manager unavailable or failed - falling back to Temurin JDK 21 tarball..."
        if ! ensure_java_linux_tarball; then
            log_err "Java auto-install did not succeed."
            java_manual_hint
            exit $ERR_JAVA
        fi
    fi
}

ensure_java() {
    if _java_ok; then
        log_ok "Java: $(java -version 2>&1 | head -n1)"
        return 0
    fi
    log_i "Java ${JDK_MAJOR_REQUIRED}+ not found. Installing OpenJDK 21..."
    case "$OS_FAMILY" in
        mac)   ensure_java_mac ;;
        linux) ensure_java_linux ;;
    esac
    if _java_ok; then
        log_ok "Java installed: $(java -version 2>&1 | head -n1)"
    else
        log_err "Java auto-install did not succeed."
        java_manual_hint
        exit $ERR_JAVA
    fi
}

ensure_curl() {
    if command -v curl &> /dev/null; then
        log_v "curl: $(curl --version 2>/dev/null | head -1 | cut -d' ' -f1-2)"
        return 0
    fi
    if command -v wget &> /dev/null; then
        log_warn "curl missing - wget found, downloads will use wget."
        return 0
    fi
    log_i "Installing curl..."
    case "$PKG_MGR" in
        apt-get) sudo apt-get update -qq && sudo apt-get install -y curl 2>&1 || true ;;
        dnf)     sudo dnf install -y curl 2>&1 || true ;;
        yum)     sudo yum install -y curl 2>&1 || true ;;
        apk)     sudo apk add --no-cache curl 2>&1 || true ;;
    esac
    if command -v curl &> /dev/null || command -v wget &> /dev/null; then
        log_ok "Downloader available."
    else
        log_err "Neither curl nor wget is available and none could be installed."
        exit $ERR_CURL
    fi
}

rg_soft_fail() {
    # Non-fatal: search falls back to a PATH-installed rg at runtime
    log_warn "rg could not be installed automatically - search support may be degraded."
    local tarball_name
    if [ "$OS_FAMILY" = "mac" ]; then
        log_warn "Manual install: brew install ripgrep"
        if [ "$ARCH" = "arm64" ]; then
            tarball_name="ripgrep-${RG_VERSION}-aarch64-apple-darwin.tar.gz"
        else
            tarball_name="ripgrep-${RG_VERSION}-x86_64-apple-darwin.tar.gz"
        fi
    else
        log_warn "Manual install: ${PKG_MGR:-apt-get} install ripgrep"
        tarball_name="ripgrep-${RG_VERSION}-x86_64-unknown-linux-musl.tar.gz"
    fi
    log_warn "Manual download: https://github.com/BurntSushi/ripgrep/releases/tag/v${RG_VERSION}"
    log_warn "Manual placement: extract 'rg' to ${INSTALL_DIR}/rg (chmod +x)"
    expected_checksum_hint "$tarball_name" || true
}

_install_rg_tarball() {
    # $1 = upstream platform suffix (apple-darwin | unknown-linux-musl)
    local tarball_name="ripgrep-${RG_VERSION}-${1}.tar.gz"
    local gh_url="https://github.com/BurntSushi/ripgrep/releases/download/${RG_VERSION}/${tarball_name}"
    local tmp_archive tmp_dir rg_bin
    tmp_archive=$(mktemp)
    tmp_dir=$(mktemp -d)
    log_i "Downloading rg ${RG_VERSION} (${1})..."
    # Source chain: COS mirror -> GitHub -> ghproxy (batch 2)
    if ! download_file "$tmp_archive" "$tarball_name" "$tarball_name" \
        "${COS_DEPS_BASE}/${tarball_name}" "$gh_url" "https://ghproxy.net/${gh_url}"; then
        rm -rf "$tmp_archive" "$tmp_dir"
        return 1
    fi
    # Portable extraction (GNU tar AND bsdtar): unpack, then find the binary
    if tar xzf "$tmp_archive" -C "$tmp_dir" 2>/dev/null; then
        rg_bin=$(find "$tmp_dir" -type f -name rg -perm -u+x 2>/dev/null | head -1)
        [ -z "$rg_bin" ] && rg_bin=$(find "$tmp_dir" -type f -name rg 2>/dev/null | head -1)
        if [ -n "$rg_bin" ]; then
            cp "$rg_bin" "${INSTALL_DIR}/rg" && chmod +x "${INSTALL_DIR}/rg"
        fi
    fi
    rm -rf "$tmp_archive" "$tmp_dir"
    if [ -x "${INSTALL_DIR}/rg" ]; then
        log_ok "rg installed to ${INSTALL_DIR}/rg"
        return 0
    fi
    return 1
}

_install_rg_distro() {
    case "$PKG_MGR" in
        apt-get) sudo apt-get update -qq && sudo apt-get install -y ripgrep 2>&1 || true ;;
        dnf)     sudo dnf install -y ripgrep 2>&1 || true ;;
        yum)     sudo yum install -y ripgrep 2>&1 || true ;;
        apk)     sudo apk add --no-cache ripgrep 2>&1 || true ;;
        *)       return 1 ;;
    esac
    command -v rg > /dev/null 2>&1
}

ensure_rg() {
    if [ -x "${INSTALL_DIR}/rg" ]; then
        log_ok "rg: cached at ${INSTALL_DIR}/rg"
        return 0
    fi
    if command -v rg &> /dev/null; then
        log_ok "rg: $(rg --version 2>/dev/null | head -1)"
        return 0
    fi
    log_i "Installing ripgrep (rg) for search support..."
    local installed=0
    case "$OS_FAMILY" in
        mac)
            if [ "$ARCH" = "arm64" ]; then
                _install_rg_tarball "aarch64-apple-darwin" && installed=1
            else
                _install_rg_tarball "x86_64-apple-darwin" && installed=1
            fi
            ;;
        linux)
            if [ "$ARCH" = "arm64" ]; then
                # No official aarch64-linux tarball upstream (verified 404,
                # 2026-09-06) - use the distro package instead.
                if _install_rg_distro; then installed=1; log_ok "rg installed via ${PKG_MGR}"; fi
            else
                if _install_rg_tarball "x86_64-unknown-linux-musl"; then
                    installed=1
                elif _install_rg_distro; then
                    installed=1; log_ok "rg installed via ${PKG_MGR}"
                fi
            fi
            ;;
    esac
    if [ "$installed" = "0" ]; then
        rg_soft_fail
    fi
}

# Download Whisper voice model for offline speech recognition (best-effort)
install_voice_model() {
    local model_dir="${HOME}/${HOME_DIR}/voice-models/onnx-community/whisper-base"
    if [ -f "$model_dir/onnx/encoder_model_quantized.onnx" ]; then
        log_v "Voice model already installed."
        return 0
    fi

    local base
    if [ "$REGION" = "cn" ]; then
        base="https://hf-mirror.com/onnx-community/whisper-base/resolve/main"
    else
        base="https://huggingface.co/onnx-community/whisper-base/resolve/main"
    fi
    log_i "Downloading Whisper voice model (~75MB, one-time)..."
    mkdir -p "$model_dir/onnx"

    # Config files (small) - [n/N] multi-file counter in the label
    local _n=0 _total_files=6
    local f
    for f in config.json tokenizer.json generation_config.json preprocessor_config.json; do
        _n=$((_n+1))
        _download "$base/$f" "$model_dir/$f" "[$_n/$_total_files] $f" 2>/dev/null || true
    done

    # Quantized ONNX models (encoder ~22MB + decoder ~51MB)
    local ok=true
    _n=$((_n+1))
    _download "$base/onnx/encoder_model_quantized.onnx" "$model_dir/onnx/encoder_model_quantized.onnx" \
        "[$_n/$_total_files] encoder_model_quantized.onnx" || ok=false
    _n=$((_n+1))
    _download "$base/onnx/decoder_model_merged_quantized.onnx" "$model_dir/onnx/decoder_model_merged_quantized.onnx" \
        "[$_n/$_total_files] decoder_model_merged_quantized.onnx" || ok=false
    if $ok; then
        log_ok "Voice model installed."
    else
        log_warn "Voice model download failed (voice will use CDN on first use)."
    fi
}

stage_deps() {
    stage_hdr 2 "Checking dependencies..."
    ensure_curl
    ensure_java
    ensure_rg
    install_voice_model
}

# ---- [3/6] jar ------------------------------------------------------------

_file_size() { stat -f %z "$1" 2>/dev/null || stat -c %s "$1" 2>/dev/null || echo 0; }

# TTY download with the brand progress bar: curl runs in the background
# writing to the target file; we poll its size and redraw the bar. Total
# size comes from a HEAD probe (content-length); unreachable -> spinner mode.
_download_progress() {  # <url> <target> <label> -> curl exit code
    local _url="$1" _target="$2" _label="$3"
    local _total
    _total=$(curl -fsSI --connect-timeout 5 --max-time 10 "$_url" 2>/dev/null \
        | tr -d '\r' | awk 'tolower($1)=="content-length:"{n=$2} END{if(n!="") printf "%d", n}')
    [ -z "$_total" ] && _total=-1
    curl -fsSL --connect-timeout 10 --max-time 120 "$_url" -o "$_target" 2>/dev/null &
    local _pid=$! _spin=0 _last=0 _now=0 _spd=-1
    while kill -0 "$_pid" 2>/dev/null; do
        _now=$(_file_size "$_target")
        _spd=$(( (_now - _last) * 2 ))   # 0.5s poll interval
        _last=$_now
        progress_render "$_now" "$_total" "$_label" "$_spd" "$_spin"
        _spin=$((_spin+1))
        sleep 0.5 2>/dev/null || sleep 1
    done
    local _rc=0
    wait "$_pid" || _rc=$?
    _now=$(_file_size "$_target")
    progress_render "$_now" "$_total" "$_label" -1 "$_spin"
    printf '\n'
    return "$_rc"
}

_download() {
    local url="$1" target="$2" label="${3:-}"
    if _progress_ok; then
        _download_progress "$url" "$target" "${label:-$(basename "$target")}"
    else
        # non-TTY (curl|bash pipe) / dumb terminal: plain one-line log
        [ -n "$label" ] && log_i "Downloading ${label}..."
        if command -v curl &> /dev/null; then
            curl -fsSL --connect-timeout 10 --max-time 120 "${url}" -o "${target}"
        elif command -v wget &> /dev/null; then
            wget --connect-timeout=10 --timeout=120 -q "${url}" -O "${target}"
        else
            log_err "curl or wget is required."
            exit $ERR_CURL
        fi
    fi
}

# ---- checksum machinery (deps/ integrity, batch 2) ------------------------

CHECKSUMS_LOADED=""
CHECKSUMS_CONTENT=""

sha256_of() {  # <file> -> hash (or empty when no tool available)
    if command -v shasum > /dev/null 2>&1; then
        shasum -a 256 "$1" 2>/dev/null | awk '{print $1}'
    elif command -v sha256sum > /dev/null 2>&1; then
        sha256sum "$1" 2>/dev/null | awk '{print $1}'
    fi
}

fetch_checksum_for() {  # <filename> -> expected sha256 (or empty = unknown)
    if [ -z "$CHECKSUMS_LOADED" ]; then
        CHECKSUMS_CONTENT=$(curl -fsSL --connect-timeout 5 --max-time 15 \
            "${COS_DEPS_BASE}/checksums.txt" 2>/dev/null || true)
        CHECKSUMS_LOADED=1
        [ -n "$CHECKSUMS_CONTENT" ] && log_v "Loaded deps/checksums.txt from COS." \
            || log_v "deps/checksums.txt unreachable - checksum verification degraded."
    fi
    [ -n "$CHECKSUMS_CONTENT" ] || return 0
    awk -v f="$1" '$2 == f { print $1; exit }' <<< "$CHECKSUMS_CONTENT"
}

expected_checksum_hint() {  # <filename> -> "sha256: <hash>" line (or empty)
    local h
    h=$(fetch_checksum_for "$1")
    [ -n "$h" ] && echo "       sha256: ${h}"
}

# Multi-source download with checksum verification. Every candidate source
# (COS first by convention) is verified against deps/checksums.txt when the
# manifest is reachable; a mismatched source is discarded and the next one
# is tried. Unknown checksum (manifest unreachable) degrades to accept.
#   download_file <target> <filename-in-manifest> <label> <url1> [url2] ...
download_file() {
    local target="$1" name="$2" label="$3"; shift 3
    local url verdict
    for url in "$@"; do
        log_v "Trying source: ${url}"
        if _download "$url" "$target" "$label"; then
            verdict=$(verify_checksum "$target" "$name") || true
            case "$verdict" in
                ok)      return 0 ;;
                bad)     rm -f "$target"; continue ;;
                unknown) return 0 ;;
            esac
        else
            rm -f "$target"
        fi
    done
    return 1
}

verify_checksum() {  # <file> <filename-in-manifest> -> echoes ok|bad|unknown
    local file="$1" name="$2" expected actual
    expected=$(fetch_checksum_for "$name")
    if [ -z "$expected" ]; then
        echo "unknown"
        return 0
    fi
    actual=$(sha256_of "$file")
    if [ -z "$actual" ]; then
        echo "unknown"   # no sha256 tool available - degrade, don't misjudge
        return 0
    fi
    if [ "$actual" = "$expected" ]; then
        echo "ok"
        return 0
    fi
    echo "bad"
    return 0
}

download_jar() {
    stage_hdr 3 "Downloading ${PRODUCT_NAME} v${VERSION}..."
    # Version-dependent names are computed here (VERSION resolves in
    # resolve_version, before this stage runs).
    JAR_NAME="${LOWER_NAME}-assembly-${VERSION}.jar"
    COS_URL="${COS_BASE_CN}/${JAR_NAME}"
    local target="${INSTALL_DIR}/${JAR_NAME}"
    mkdir -p "${INSTALL_DIR}"

    # Idempotency: same version already in place -> skip (no re-download)
    if [ -f "${target}" ]; then
        log_ok "Already up-to-date (v${VERSION})."
        return 0
    fi

    # Remove old JAR files (keep user data untouched)
    local old_jars
    old_jars=$(ls "${INSTALL_DIR}"/${LOWER_NAME}-assembly-*.jar "${INSTALL_DIR}"/nebflow-assembly-*.jar 2>/dev/null || true)
    if [ -n "$old_jars" ]; then
        log_i "Removing old version(s)..."
        rm -f "${INSTALL_DIR}"/${LOWER_NAME}-assembly-*.jar "${INSTALL_DIR}"/nebflow-assembly-*.jar
    fi

    # #29: 仓库 private 后 GitHub Releases 未认证 404——COS 单一源
    if _download "${COS_URL}" "${target}" "${JAR_NAME}"; then
        log_ok "Downloaded ${JAR_NAME} from COS."
        return 0
    fi
    log_err "Download failed from COS. Check ${COS_URL}"
    exit $ERR_JAR
}

# ---- [4/6] wrapper + PATH -------------------------------------------------

# Create wrapper script
create_wrapper() {
    local wrapper="${INSTALL_DIR}/${WRAPPER_NAME}"
    log_i "Creating wrapper script..."
    # Unquoted delimiter: ${LOWER_NAME}/${PRODUCT_NAME} expand NOW (generation
    # time, from the brand block above); runtime expansions are escaped as \$.
    # (Bug fix: the old quoted 'WRAPPER' delimiter emitted the variables as
    # literals, so the wrapper's jar glob never matched -> nebflow CLI dead.)
    cat > "${wrapper}" << WRAPPER
#!/bin/bash
SCRIPT_DIR="\$(cd "\$(dirname "\$0")" && pwd)"
JAVA_BIN="\$(command -v java || echo "\$HOME/${HOME_DIR}/jdk-21/bin/java")"
JAR=\$(ls -1 "\${SCRIPT_DIR}"/${LOWER_NAME}-assembly-*.jar 2>/dev/null | head -n1)
if [ -z "\$JAR" ]; then
    echo "ERROR: ${PRODUCT_NAME} JAR not found in \${SCRIPT_DIR}"
    exit 1
fi
exec "\$JAVA_BIN" --add-opens java.base/java.lang=ALL-UNNAMED -jar "\$JAR" "\$@"
WRAPPER
    chmod +x "${wrapper}"
    log_ok "Wrapper created: ${wrapper}"
}

# Add install dir to PATH in shell profile
setup_path() {
    local profile=""
    if [ -f "${HOME}/.zshrc" ]; then
        profile="${HOME}/.zshrc"
    elif [ -f "${HOME}/.bashrc" ]; then
        profile="${HOME}/.bashrc"
    elif [ -f "${HOME}/.bash_profile" ]; then
        profile="${HOME}/.bash_profile"
    fi
    if [ -n "$profile" ] && ! grep -q "\.nebflow/bin" "$profile" 2>/dev/null; then
        echo "" >> "$profile"
        echo "# Added by ${PRODUCT_NAME} installer" >> "$profile"
        echo "export PATH=\"\$HOME/${HOME_DIR}/bin:\$PATH\"" >> "$profile"
        log_i "Added ~/${HOME_DIR}/bin to PATH in $profile"
    else
        log_v "PATH already configured."
    fi
}

stage_wrapper() {
    stage_hdr 4 "Writing launcher and PATH..."
    create_wrapper
    setup_path
}

# ---- [5/6] config ---------------------------------------------------------

# Create config template
create_config() {
    local config_dir="${HOME}/${HOME_DIR}"
    local config_file="${config_dir}/${CONFIG_FILE}"
    if [ ! -f "${config_file}" ]; then
        log_i "Creating default config at ${config_file}..."
        mkdir -p "${config_dir}"
        echo '{}' > "${config_file}"
        log_ok "Config created: ${config_file}"
    else
        log_v "Config already exists."
    fi
}

# Installer manifest (SCRIPT_VERSION + environment) for `nebflow update`
# and diagnostics. Overwritten on each (re)install.
write_manifest() {
    local manifest="${HOME}/${HOME_DIR}/install-manifest.json"
    mkdir -p "${HOME}/${HOME_DIR}"
    cat > "${manifest}" << MANIFEST
{
  "scriptVersion": "${SCRIPT_VERSION}",
  "product": "${PRODUCT_NAME}",
  "version": "${VERSION}",
  "channel": "${CHANNEL}",
  "region": "${REGION}",
  "os": "${OS_FAMILY}",
  "arch": "${ARCH}",
  "installDir": "${INSTALL_DIR}",
  "installedAt": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
}
MANIFEST
    log_v "Manifest written: ${manifest}"
}

stage_config() {
    stage_hdr 5 "Setting up config..."
    create_config
    write_manifest
}

# ---- [6/6] done -----------------------------------------------------------

stage_finish() {
    stage_hdr 6 "Done!"
    echo ""
    echo "[ok] ${PRODUCT_NAME} v${VERSION} installed."
    echo "     Run: ${WRAPPER_NAME} --help"
    echo "     Config: ~/${HOME_DIR}/${CONFIG_FILE}"
    echo "     Please restart your terminal or run: export PATH=\"\$HOME/${HOME_DIR}/bin:\$PATH\""
}

# ---- pipeline -------------------------------------------------------------
resolve_version
print_banner
stage_env
stage_deps
download_jar
stage_wrapper
stage_config
stage_finish
