package nebflow.actor

import cats.effect.IO
import nebflow.core.NebflowLogger

/**
 * System signals — delivered via a separate channel from regular messages.
 * Actors handle them via [[Behavior.onSignal]].
 *
 * Unlike regular messages, system signals are generated by the ActorSystem
 * itself (e.g. death watch notifications).
 */
sealed trait SystemSignal

object SystemSignal:
  /**
   * Delivered to an actor that called [[ActorContext.watch]] when the
   * watched actor's Fiber terminates (normal stop, crash, or cancellation).
   */
  case class Terminated(ref: ActorRef[?]) extends SystemSignal
end SystemSignal

/**
 * An actor's behavior: process one message, return the next behavior.
 *
 * State is carried through the returned behavior's closure. This is the
 * classic Actor model pattern — each message handler returns the next
 * behavior, carrying the updated state.
 *
 * The key difference from Pekko: receive returns IO[Behavior[Msg]],
 * making the message handler cancelable, composable, and resource-safe.
 */
trait Behavior[Msg]:
  def receive(ctx: ActorContext[Msg], msg: Msg): IO[Behavior[Msg]]
  def isStopped: Boolean = false

  /** Called on actor spawn. Setup behaviors override to initialize context. */
  def onStart(ctx: ActorContext[Msg]): IO[Behavior[Msg]] = IO.pure(this)

  /** System signal handler (death watch, etc). Default: ignore. */
  def onSignal(ctx: ActorContext[Msg], signal: SystemSignal): IO[Behavior[Msg]] = IO.pure(this)

  /**
   * Cleanup hook — guaranteed to run once when the actor stops, regardless
   * of how it stops (normal, crash, cancelled). Default: no-op.
   */
  def onStop(ctx: ActorContext[Msg]): IO[Unit] = IO.unit

  /**
   * Error handler — called when [[receive]] throws. Default: log and resume
   * with same behavior. Override to return a safe fallback behavior (e.g. idle).
   */
  def onError(ctx: ActorContext[Msg], err: Throwable): IO[Behavior[Msg]] =
    ctx.log.error(s"Actor error: ${err.getMessage}").as(this)
end Behavior

object Behaviors:

  /** Setup behavior — runs factory on spawn to produce initial behavior. */
  final case class Setup[Msg](factory: ActorContext[Msg] => IO[Behavior[Msg]]) extends Behavior[Msg]:

    def receive(ctx: ActorContext[Msg], msg: Msg): IO[Behavior[Msg]] =
      factory(ctx).flatMap(_.receive(ctx, msg))
    override def onStart(ctx: ActorContext[Msg]): IO[Behavior[Msg]] = factory(ctx)

  /** Setup: initialize context on spawn, return initial behavior. */
  def setup[Msg](factory: ActorContext[Msg] => IO[Behavior[Msg]]): Behavior[Msg] =
    Setup(factory)

  /** Pure message handler — most common. */
  def receiveMessage[Msg](handler: Msg => IO[Behavior[Msg]]): Behavior[Msg] = new:
    def receive(ctx: ActorContext[Msg], msg: Msg): IO[Behavior[Msg]] = handler(msg)

  /** Message handler with context access. */
  def receive[Msg](handler: (ActorContext[Msg], Msg) => IO[Behavior[Msg]]): Behavior[Msg] = new:
    def receive(ctx: ActorContext[Msg], msg: Msg): IO[Behavior[Msg]] = handler(ctx, msg)

  /** Terminal behavior — actor stops after returning this. */
  object Stopped extends Behavior[Nothing]:

    def receive(ctx: ActorContext[Nothing], msg: Nothing): IO[Behavior[Nothing]] =
      IO.pure(this)
    override def isStopped: Boolean = true

  def stopped[Msg]: Behavior[Msg] = Stopped.asInstanceOf[Behavior[Msg]]
end Behaviors
