package nebflow.core.tools

import cats.effect.unsafe.implicits.global
import io.circe.{Json, JsonObject}
import munit.FunSuite

import java.nio.file.{Files, Path, Paths}

/**
 * imgref-impl (2026-09-18, author order) — the TWO author-visible failures of
 * 2026-09-18, pinned at the tool face, both about a path that contains a SPACE.
 *
 * Author evidence (verbatim meaning): with a NO-space path under the data root
 * the card rendered fine; with a space-bearing path it failed twice — ① a `%20`
 * spelling reached Card and the resolver looked for a literal `…/Claude%20code/…`
 * (`not-found`, "the nearest existing parent directory is …/evidence"), and
 * ② the raw space path produced a `proxied` count while the frontend `<img>`
 * still failed to load.
 *
 * Fixtures are built HERE (a temp directory whose ANCESTOR segment contains a
 * space, plus a real, decodable PNG generated by [[writePng]]) — never a mock,
 * never a 0-byte placeholder, and never a machine-specific absolute path, so the
 * spec is portable. The PNG is large enough that its base64 `data:` URI exceeds
 * the 40,000-char inline budget: it therefore stays on the `/api/nf-file`
 * reference leg, which is the leg under test.
 *
 * Four reference forms of the SAME real file, each asserted end to end:
 *   raw (literal spaces) / `%20` / `+` / mixed.
 */
class CardToolPathFormSpec extends FunSuite:

  private val ctx = ToolContext(projectRoot = os.pwd.toString)
  private val sentinel = "___CARD_HTML___"

  private var root: Path = null
  private var spaceDir: Path = null

  private var spaceImage: Path = null
  private var spaceCss: Path = null
  private var ctlCss: Path = null

  override def beforeAll(): Unit =
    root = Files.createTempDirectory("imgref-form-")
    // a space in an ANCESTOR segment AND in the file name — the author's shape
    spaceDir = root.resolve("space dir")
    Files.createDirectories(spaceDir)
    spaceImage = writePng(spaceDir.resolve("fetch leg big space.png"), 200, 200, 7)
    spaceCss = spaceDir.resolve("ref style.css")
    Files.write(spaceCss, ".x{color:#123456}\n".getBytes("UTF-8"))
    ctlCss = root.resolve("control-nospace.css")
    Files.write(ctlCss, ".y{color:#654321}\n".getBytes("UTF-8"))

  override def afterAll(): Unit =
    if root != null then
      val s = Files.walk(root)
      try
        s.sorted(java.util.Comparator.reverseOrder()).forEach { x =>
          try Files.deleteIfExists(x)
          catch case _: Throwable => ()
        }
      finally s.close()

  // ── the real fixture ──────────────────────────────────────────────────────

  /**
   * A REAL, browser-decodable RGB PNG: 8-bit truecolour, no interlace, one PNG
   * filter byte per row, `IDAT` deflated with `java.util.zip`, CRCs computed —
   * i.e. the bytes a browser can actually decode (`naturalWidth == w`), not a
   * mock or a placeholder. Pseudo-random pixels keep it incompressible, so a
   * 200×200 image stays far above the inline budget.
   */
  private def writePng(path: Path, w: Int, h: Int, seed: Int): Path =
    def be32(v: Int): Array[Byte] =
      Array((v >>> 24).toByte, (v >>> 16).toByte, (v >>> 8).toByte, v.toByte)
    def chunk(name: String, data: Array[Byte]): Array[Byte] =
      val nb = name.getBytes("US-ASCII")
      val crc = new java.util.zip.CRC32()
      crc.update(nb)
      crc.update(data)
      be32(data.length) ++ nb ++ data ++ be32(crc.getValue.toInt)
    val rnd = new java.util.Random(seed)
    val rows = new java.io.ByteArrayOutputStream()
    val row = new Array[Byte](1 + w * 3)
    var y = 0
    while y < h do
      row(0) = 0 // filter type 0 (None)
      var x = 0
      while x < w do
        row(1 + x * 3) = rnd.nextInt(256).toByte
        row(2 + x * 3) = rnd.nextInt(256).toByte
        row(3 + x * 3) = rnd.nextInt(256).toByte
        x += 1
      rows.write(row)
      y += 1
    val deflated = new java.io.ByteArrayOutputStream()
    val ds = new java.util.zip.DeflaterOutputStream(deflated)
    ds.write(rows.toByteArray)
    ds.finish()
    ds.close()
    val header = be32(w) ++ be32(h) ++ Array[Byte](8, 2, 0, 0, 0) // bit depth 8, colour type 2 (RGB)
    val out = new java.io.ByteArrayOutputStream()
    out.write(Array[Byte](0x89.toByte, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a))
    out.write(chunk("IHDR", header))
    out.write(chunk("IDAT", deflated.toByteArray))
    out.write(chunk("IEND", Array.emptyByteArray))
    Files.write(path, out.toByteArray)
    path
  end writePng

  // ── payload helpers ───────────────────────────────────────────────────────

  private def card(html: String): Json =
    val input = JsonObject("html" -> Json.fromString(html), "title" -> Json.fromString("T"))
    val result = CardTool.call(input, ctx).unsafeRunSync().getOrElse(fail("expected Right"))
    assert(result.startsWith(sentinel), s"result must start with the sentinel, got: ${result.take(60)}")
    io.circe.parser.parse(result.substring(sentinel.length)).fold(err => fail(s"payload JSON: $err"), identity)

  private def htmlOf(p: Json): String = p.hcursor.get[String]("html").toOption.getOrElse("")
  private def warningsOf(p: Json): List[Json] = p.hcursor.get[List[Json]]("warnings").toOption.getOrElse(Nil)
  private def notesOf(p: Json): List[String] = p.hcursor.get[List[String]]("notes").toOption.getOrElse(Nil)

  private def refs(p: Json, field: String): Int =
    p.hcursor.downField("fileRefs").get[Int](field).toOption.getOrElse(-1)

  /**
   * The ONE producer/consumer pair, restated independently of the production
   * single source: `%20` out (never `+`), bare `+` folded back to a space on the
   * way in (a literal plus is spelled `%2B`). If the production codec ever
   * drifts from this pair, these assertions fail here.
   */
  private def canonicalEncode(p: String): String =
    java.net.URLEncoder.encode(p, "UTF-8").replace("+", "%20")

  private def canonicalDecode(s: String): Option[String] =
    try Some(java.net.URLDecoder.decode(s.replace("+", " "), "UTF-8"))
    catch case _: Exception => None

  private val emittedPathRe = raw"""/api/nf-file\?path=([^&"')]+)""".r

  private def emittedPath(html: String): String =
    emittedPathRe
      .findFirstMatchIn(html)
      .map(_.group(1))
      .getOrElse(fail(s"no /api/nf-file URL in: ${html.take(300)}"))

  private def forms(plain: String): List[(String, String)] =
    List(
      "raw" -> plain,
      "pct20" -> plain.replace(" ", "%20"),
      "plus" -> plain.replace(" ", "+"),
      "mixed" -> plain.replace(" ", "%20").replaceFirst("space%20dir", "space+dir")
    )

  // ── ① every spelling of a space-bearing path must resolve, and round-trip ──

  test("space path: every one of the four reference forms resolves and round-trips (①)"):
    val real = spaceCss.toRealPath().toString
    forms(real).foreach { (label, value) =>
      val p = card(s"""<link rel="stylesheet" href="$value"/>""")
      val ws = warningsOf(p)
      assert(
        ws.isEmpty,
        s"$label: the reference must resolve to the real file; warnings=${ws.map(_.noSpaces).mkString(",")}"
      )
      assertEquals(refs(p, "proxied"), 1, s"$label: exactly one proxied reference")
      assertEquals(refs(p, "failed"), 0, s"$label: no failures counted")
      val emitted = emittedPath(htmlOf(p))
      assertEquals(canonicalDecode(emitted), Some(real), s"$label: the emitted URL must decode back to the real path")
      assertEquals(canonicalEncode(real), emitted, s"$label: the emitted form must be the single-source `%20` form")
      if label != "raw" then assert(notesOf(p).nonEmpty, s"$label: a decoded-form hit must be disclosed in `notes`")
      else assertEquals(notesOf(p), Nil, "raw: the raw form hit — no disclosure needed")
    }

  test("space path: a >budget image stays on the /api/nf-file reference leg and round-trips (②)"):
    val real = spaceImage.toRealPath().toString
    assert(Files.size(spaceImage) > 30000, s"fixture must exceed the inline budget: ${Files.size(spaceImage)} bytes")
    val p = card(s"""<img src="$real"/>""")
    assertEquals(warningsOf(p), Nil)
    assertEquals(refs(p, "proxied"), 1, "a data URI over 40,000 chars exceeds the budget — reference leg")
    assertEquals(refs(p, "inlined"), 0)
    val emitted = emittedPath(htmlOf(p))
    assertEquals(canonicalDecode(emitted), Some(real))
    assert(!emitted.contains("+"), "the emitted URL must not carry a bare `+` for a space")
    assertEquals(canonicalEncode(real), emitted, "the emitted form must be the single-source `%20` form")

  // ── 阳性对照：无空格路径（作者屏上本就绿的那一形） ────────────────────────────

  test("control: the no-space path keeps its previous byte-identical URL"):
    val real = ctlCss.toRealPath().toString
    val p = card(s"""<link rel="stylesheet" href="$real"/>""")
    assertEquals(warningsOf(p), Nil)
    assertEquals(refs(p, "proxied"), 1)
    assertEquals(
      htmlOf(p),
      s"""<link rel="stylesheet" href="/api/nf-file?path=${canonicalEncode(real)}"/>"""
    )

  // ── 负对照：真文件但在不可服务命名空间内 ⇒ 警告 + 不计 proxied ─────────────────

  test("leg scope: the same unservable location warns on the URL face and still embeds on the resource face"):
    // 返工 r2（2026-09-18 复核位 F1）：「端点不可达」与「不可内联」是两件事。封面
    // （`<link href>`）只能靠 /api/nf-file 取回 ⇒ 端点拒它就报它；图面（`<img src>`）
    // 由工具自己把字节嵌进载荷、根本不问端点 ⇒ 端点那层可达性判据不适用（这正是
    // 作者屏上 `evidence` 里的两起失败之外的常见形态，也是基线的行为）。
    val dir = Paths.get(os.pwd.toString).toRealPath().resolve(".nebflow/secrets/imgref-spec")
    Files.createDirectories(dir)
    val real = writePng(dir.resolve("servable face space.png"), 24, 18, 5)
    val link = dir.resolve("link face.png")
    Files.write(link, Array[Byte](1, 2, 3))
    try
      val asImage = card(s"""<img src="$real"/>""")
      println(
        s"[PATH-FORM-READING] img-face fileRefs=${asImage.hcursor.downField("fileRefs").focus.map(_.noSpaces)} " +
          s"warnings=${warningsOf(asImage).map(_.noSpaces).mkString(",")}"
      )
      assertEquals(refs(asImage, "inlined"), 1, "the bytes ride in the payload: no endpoint involved")
      assertEquals(refs(asImage, "proxied"), 0, "an embedded image emits no /api/nf-file URL")
      assertEquals(refs(asImage, "failed"), 0)
      assertEquals(warningsOf(asImage), Nil)
      assert(htmlOf(asImage).contains("data:image/png;base64,"), "the data: URI is in the markup")
      assert(!htmlOf(asImage).contains("/api/nf-file"), "no URL was emitted for the embedded reference")

      val asLink = card(s"""<link rel="stylesheet" href="$link"/>""")
      println(
        s"[PATH-FORM-READING] link-face fileRefs=${asLink.hcursor.downField("fileRefs").focus.map(_.noSpaces)} " +
          s"warnings=${warningsOf(asLink).map(_.noSpaces).mkString(",")}"
      )
      assertEquals(refs(asLink, "proxied"), 0, "the URL leg cannot be counted when the endpoint refuses")
      assertEquals(refs(asLink, "inlined"), 0, "a navigation reference is never embedded")
      assertEquals(refs(asLink, "failed"), 1)
      assert(
        warningsOf(asLink).exists(_.noSpaces.contains("not-servable")),
        s"the URL-face refusal is reported: ${warningsOf(asLink).map(_.noSpaces).mkString(",")}"
      )
    finally
      Files.deleteIfExists(real)
      Files.deleteIfExists(link)
      Files.deleteIfExists(dir)

    end try

  test("negative control: a real file in an unservable namespace is warned, never counted"):
    val dir = Paths.get(os.pwd.toString).toRealPath().resolve(".nebflow/secrets/imgref-spec")
    Files.createDirectories(dir)
    val f = dir.resolve("negative.png")
    Files.write(f, Array[Byte](1, 2, 3))
    try
      val p = card(s"""<link rel="stylesheet" href="$f"/>""")
      assert(warningsOf(p).nonEmpty, "an unservable reference must warn")
      assertEquals(refs(p, "proxied"), 0, "an unservable reference must NOT be counted as proxied")
      assertEquals(refs(p, "failed"), 1)
      assert(htmlOf(p).contains(f.toString), "the raw value stays in the markup (no blank rewrite)")
      assert(
        warningsOf(p).exists(_.noSpaces.contains("not-servable")),
        s"the refusal must name the reason: ${warningsOf(p).map(_.noSpaces).mkString(",")}"
      )
    finally
      // rework r1 (verifier C1): clean up ONLY the subtree this spec created —
      // `dir.getParent` is the PRE-EXISTING `.nebflow/secrets` directory (it
      // holds real files in a configured checkout), and deleting it made the
      // suite fail with `DirectoryNotEmptyException` in any run that had
      // anything else living there. A test must never remove a directory it did
      // not create.
      Files.deleteIfExists(f)
      Files.deleteIfExists(dir)
    end try

  // ── 负对照：0 字节文件（浏览器同样渲染不出来）⇒ 警告 + 不计 proxied ──────────

  test("negative control: a 0-byte file is warned, never counted, never inlined"):
    val dir = Paths.get(os.pwd.toString).toRealPath().resolve(".nebflow/evidence/imgref-spec")
    Files.createDirectories(dir)
    val f = dir.resolve("zero byte space.png")
    Files.write(f, Array.emptyByteArray)
    try
      val p = card(s"""<img src="$f"/>""")
      assert(warningsOf(p).nonEmpty, "a 0-byte image must warn (its bytes cannot be rendered)")
      assertEquals(refs(p, "proxied"), 0, "a 0-byte file must not be counted as proxied")
      assert(
        warningsOf(p).exists(_.noSpaces.contains("not-readable")),
        s"the refusal must name the reason: ${warningsOf(p).map(_.noSpaces).mkString(",")}"
      )
    finally
      // rework r1 (verifier C1): self-created subtree only — see the note above.
      Files.deleteIfExists(f)
      Files.deleteIfExists(dir)
end CardToolPathFormSpec
